/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumberish,
  BytesLike,
  FunctionFragment,
  Result,
  Interface,
  EventFragment,
  AddressLike,
  ContractRunner,
  ContractMethod,
  Listener,
} from "ethers";
import type {
  TypedContractEvent,
  TypedDeferredTopicFilter,
  TypedEventLog,
  TypedLogDescription,
  TypedListener,
  TypedContractMethod,
} from "../common";

export interface IDGAFChainBridgeInterface extends Interface {
  getFunction(
    nameOrSignature:
      | "idgafToken"
      | "initiateWithdrawal"
      | "monadBridge"
      | "owner"
      | "processDeposit"
      | "processedDeposits"
      | "processedWithdrawals"
      | "renounceOwnership"
      | "setMonadBridge"
      | "transferOwnership"
  ): FunctionFragment;

  getEvent(
    nameOrSignatureOrTopic:
      | "DepositProcessed"
      | "MonadBridgeUpdated"
      | "OwnershipTransferred"
      | "WithdrawalInitiated"
  ): EventFragment;

  encodeFunctionData(
    functionFragment: "idgafToken",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "initiateWithdrawal",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "monadBridge",
    values?: undefined
  ): string;
  encodeFunctionData(functionFragment: "owner", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "processDeposit",
    values: [AddressLike, BigNumberish, BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "processedDeposits",
    values: [BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "processedWithdrawals",
    values: [BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "renounceOwnership",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "setMonadBridge",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "transferOwnership",
    values: [AddressLike]
  ): string;

  decodeFunctionResult(functionFragment: "idgafToken", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "initiateWithdrawal",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "monadBridge",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "owner", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "processDeposit",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "processedDeposits",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "processedWithdrawals",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "renounceOwnership",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "setMonadBridge",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "transferOwnership",
    data: BytesLike
  ): Result;
}

export namespace DepositProcessedEvent {
  export type InputTuple = [
    user: AddressLike,
    amount: BigNumberish,
    depositId: BytesLike,
    timestamp: BigNumberish
  ];
  export type OutputTuple = [
    user: string,
    amount: bigint,
    depositId: string,
    timestamp: bigint
  ];
  export interface OutputObject {
    user: string;
    amount: bigint;
    depositId: string;
    timestamp: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace MonadBridgeUpdatedEvent {
  export type InputTuple = [oldBridge: AddressLike, newBridge: AddressLike];
  export type OutputTuple = [oldBridge: string, newBridge: string];
  export interface OutputObject {
    oldBridge: string;
    newBridge: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace OwnershipTransferredEvent {
  export type InputTuple = [previousOwner: AddressLike, newOwner: AddressLike];
  export type OutputTuple = [previousOwner: string, newOwner: string];
  export interface OutputObject {
    previousOwner: string;
    newOwner: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace WithdrawalInitiatedEvent {
  export type InputTuple = [
    user: AddressLike,
    amount: BigNumberish,
    withdrawalId: BytesLike,
    timestamp: BigNumberish
  ];
  export type OutputTuple = [
    user: string,
    amount: bigint,
    withdrawalId: string,
    timestamp: bigint
  ];
  export interface OutputObject {
    user: string;
    amount: bigint;
    withdrawalId: string;
    timestamp: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export interface IDGAFChainBridge extends BaseContract {
  connect(runner?: ContractRunner | null): IDGAFChainBridge;
  waitForDeployment(): Promise<this>;

  interface: IDGAFChainBridgeInterface;

  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  on<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  once<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  once<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>;
  removeAllListeners<TCEvent extends TypedContractEvent>(
    event?: TCEvent
  ): Promise<this>;

  idgafToken: TypedContractMethod<[], [string], "view">;

  initiateWithdrawal: TypedContractMethod<
    [amount: BigNumberish],
    [void],
    "nonpayable"
  >;

  monadBridge: TypedContractMethod<[], [string], "view">;

  owner: TypedContractMethod<[], [string], "view">;

  processDeposit: TypedContractMethod<
    [user: AddressLike, amount: BigNumberish, depositId: BytesLike],
    [void],
    "nonpayable"
  >;

  processedDeposits: TypedContractMethod<[arg0: BytesLike], [boolean], "view">;

  processedWithdrawals: TypedContractMethod<
    [arg0: BytesLike],
    [boolean],
    "view"
  >;

  renounceOwnership: TypedContractMethod<[], [void], "nonpayable">;

  setMonadBridge: TypedContractMethod<
    [_monadBridge: AddressLike],
    [void],
    "nonpayable"
  >;

  transferOwnership: TypedContractMethod<
    [newOwner: AddressLike],
    [void],
    "nonpayable"
  >;

  getFunction<T extends ContractMethod = ContractMethod>(
    key: string | FunctionFragment
  ): T;

  getFunction(
    nameOrSignature: "idgafToken"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "initiateWithdrawal"
  ): TypedContractMethod<[amount: BigNumberish], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "monadBridge"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "owner"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "processDeposit"
  ): TypedContractMethod<
    [user: AddressLike, amount: BigNumberish, depositId: BytesLike],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "processedDeposits"
  ): TypedContractMethod<[arg0: BytesLike], [boolean], "view">;
  getFunction(
    nameOrSignature: "processedWithdrawals"
  ): TypedContractMethod<[arg0: BytesLike], [boolean], "view">;
  getFunction(
    nameOrSignature: "renounceOwnership"
  ): TypedContractMethod<[], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "setMonadBridge"
  ): TypedContractMethod<[_monadBridge: AddressLike], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "transferOwnership"
  ): TypedContractMethod<[newOwner: AddressLike], [void], "nonpayable">;

  getEvent(
    key: "DepositProcessed"
  ): TypedContractEvent<
    DepositProcessedEvent.InputTuple,
    DepositProcessedEvent.OutputTuple,
    DepositProcessedEvent.OutputObject
  >;
  getEvent(
    key: "MonadBridgeUpdated"
  ): TypedContractEvent<
    MonadBridgeUpdatedEvent.InputTuple,
    MonadBridgeUpdatedEvent.OutputTuple,
    MonadBridgeUpdatedEvent.OutputObject
  >;
  getEvent(
    key: "OwnershipTransferred"
  ): TypedContractEvent<
    OwnershipTransferredEvent.InputTuple,
    OwnershipTransferredEvent.OutputTuple,
    OwnershipTransferredEvent.OutputObject
  >;
  getEvent(
    key: "WithdrawalInitiated"
  ): TypedContractEvent<
    WithdrawalInitiatedEvent.InputTuple,
    WithdrawalInitiatedEvent.OutputTuple,
    WithdrawalInitiatedEvent.OutputObject
  >;

  filters: {
    "DepositProcessed(address,uint256,bytes32,uint256)": TypedContractEvent<
      DepositProcessedEvent.InputTuple,
      DepositProcessedEvent.OutputTuple,
      DepositProcessedEvent.OutputObject
    >;
    DepositProcessed: TypedContractEvent<
      DepositProcessedEvent.InputTuple,
      DepositProcessedEvent.OutputTuple,
      DepositProcessedEvent.OutputObject
    >;

    "MonadBridgeUpdated(address,address)": TypedContractEvent<
      MonadBridgeUpdatedEvent.InputTuple,
      MonadBridgeUpdatedEvent.OutputTuple,
      MonadBridgeUpdatedEvent.OutputObject
    >;
    MonadBridgeUpdated: TypedContractEvent<
      MonadBridgeUpdatedEvent.InputTuple,
      MonadBridgeUpdatedEvent.OutputTuple,
      MonadBridgeUpdatedEvent.OutputObject
    >;

    "OwnershipTransferred(address,address)": TypedContractEvent<
      OwnershipTransferredEvent.InputTuple,
      OwnershipTransferredEvent.OutputTuple,
      OwnershipTransferredEvent.OutputObject
    >;
    OwnershipTransferred: TypedContractEvent<
      OwnershipTransferredEvent.InputTuple,
      OwnershipTransferredEvent.OutputTuple,
      OwnershipTransferredEvent.OutputObject
    >;

    "WithdrawalInitiated(address,uint256,bytes32,uint256)": TypedContractEvent<
      WithdrawalInitiatedEvent.InputTuple,
      WithdrawalInitiatedEvent.OutputTuple,
      WithdrawalInitiatedEvent.OutputObject
    >;
    WithdrawalInitiated: TypedContractEvent<
      WithdrawalInitiatedEvent.InputTuple,
      WithdrawalInitiatedEvent.OutputTuple,
      WithdrawalInitiatedEvent.OutputObject
    >;
  };
}
