/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type * as interfaces from "./interfaces";
export type { interfaces };
export type { IDGAFBridge } from "./IDGAFBridge";
export type { IDGAFChainBridge } from "./IDGAFChainBridge";
export type { IDGAFTokenL2 } from "./IDGAFTokenL2";
